---

- name: Fail if os family is not redhat or debian or Mac
  fail:
    msg: Current role does not support on {{ ansible_os_family | lower }}, It only supports CentOS/RedHat, Debian and MacOS hosts.
  when: (ansible_os_family | lower) not in ['redhat', 'debian', 'darwin']

- name: validate vars
  include_tasks: tasks/variables.yml

- name: prerequisite
  include_tasks: "tasks/{{ ansible_os_family | lower }}-prerequisite.yml"
  when: (ansible_os_family | lower) in ['redhat', 'debian']

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: 
    - state|default('present') == 'present'

- name: track versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-track-versions.yml"
  when: 
    - state|default('present') == 'present'

- name: remove archived versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-remove-archived.yml"
  when: 
    - state|default('present') == 'present'

- name: clear temp folder
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-clear-temp.yml"
  when: 
    - clear_temp_folder | default('no') | bool

- name: uninstall
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-uninstall.yml"
  when: state|default('present') == 'absent'
