
- name: start the service
  systemd:
    state: started
    daemon_reload: yes
    name: "{{ service_name }}"
    enabled: yes
  become: yes

- name: wait for service to start
  health_check:
    url: "http://localhost:{{ health_check_port | default(server_port) }}{{ health_check_uri | default('/manage/info') }}"
    expected_status: "{{ health_check_status | default('200') }}"
    max_retries: "{{ health_check_max_retries | default('20') }}"

- name: get installed version
  uri:
    url: "http://localhost:{{ health_check_port | default(server_port) }}{{ health_check_uri | default('/manage/info') }}"
    return_content: yes
  register: api_response

- name: print installed version
  debug:
    msg: " Installed version: {{ api_response.json.build.version }}"

- name: fail if app_version is not equal to installed version
  fail:
    msg: "app_version: {{ app_version }} does not macthed to installed version {{ api_response.json.build.version }}"
  when: app_version != api_response.json.build.version